name: ppub

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0
  meta: ^1.12.0

dev_dependencies:
  ppub_dev:
