name: ppub

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.18.1
  meta: ^1.10.0

dev_dependencies:
  ppub_dev:
