arb-dir: lib/localization/arb
template-arb-file: intl_de.arb
output-localization-file: localizations.g.dart
output-class: PAppL10n
nullable-getter: false
output-dir: lib/localization/generated
synthetic-package: false
