name: purrfect
description: "A purrfect example of a to-do app."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pcore:
  pdatabase_client:
  ppub:
  ptasks_repository:

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  ppub_dev:

flutter:
  uses-material-design: true
