name: purrfect
description: "A purrfect example of a to-do app."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ppub:

dev_dependencies:
  ppub_dev:

flutter:
  uses-material-design: true
